### ISSUE TITLE
Question about hash_to_field

### ISSUE THREAD

**Issue by Dimo99** [yi-sun/circom-pairing#14]
Why did you decide to not implement a circuit for hash_to_field.
And do you think such a circuit could easily be implemented?

**Comment by jonathanpwang** [comment]
We did not implement it, but the team behind [GIP-57](https://forum.gnosis.io/t/gip-57-should-gnosis-dao-support-research-of-a-zksnark-enabled-light-client-and-bridge/5421) has implement hash_to_field. The code is not yet public but it will be open sourced soon.
