### ISSUE TITLE
c++ compiled code can not run in centos

### ISSUE THREAD

**Issue by lordharrd** [yi-sun/circom-pairing#18]
Hi:

After compiling witness generation code, the VERIFYING WITNESS step is failed on centos(works on my mac but it's tooooo slow)

`
****COMPILING C++ WITNESS GENERATION CODE****

g++ -c main.cpp -std=c++11 -O3 -I.

g++ -c calcwit.cpp -std=c++11 -O3 -I.

g++ -c fr.cpp -std=c++11 -O3 -I.

nasm -felf64 fr.asm -o fr_asm.o

g++ -c signature.cpp -std=c++11 -O3 -I.

g++ -o signature *.o -lgmp

DONE (43s)

****VERIFYING WITNESS****

./build_signature.sh: line 37: 17543 illegal hardware instruction            ./"$CIRCUIT_NAME" ../../../scripts/"$CIRCUIT_NAME"/input_"$CIRCUIT_NAME".json ../witness.wtns

DONE (0s)
`

i try to run the compiled code individual got the same issue
`
circom-pairing git:(master) ✗ ./build/signature/signature_cpp/signature

[1]    17605 illegal hardware instruction  ./build/signature/signature_cpp/signature
`

**Comment by jonathanpwang** [comment]
The `./build/signature/signature_cpp/signature` binary does exist? 
If so, weird... The C++ compilation requires certain hardware architecture, so it may be related to that. You'd have to check the C++ dependencies of the circom compiler with your system. That's my best guess.

**Comment by lordharrd** [comment]
> The `./build/signature/signature_cpp/signature` binary does exist? If so, weird... The C++ compilation requires certain hardware architecture, so it may be related to that. You'd have to check the C++ dependencies of the circom compiler with your system. That's my best guess.
Yeah, my server cpu is not support..
https://github.com/fluidex/snarkit2/blob/70142d8bbc5ec79cfa6869205263ff77e8423975/src/witness_generator.ts
ADX and BMI2 cpu features needed in circom x64 assembly
I use js witness for now thanks..
