### ISSUE TITLE
Avoiding 0 signatures / public keys

### ISSUE THREAD

**Issue by adelapie** [yi-sun/circom-pairing#7]
Hi,

Nice project! I have the feeling the components at https://github.com/yi-sun/circom-pairing/blob/master/circuits/bls_signature.circom does not check if the signature and public key are 0 but I might be wrong:

```
// Inputs:
//   - pubkey as element of E(Fq)
//   - hash represents two field elements in Fp2, in practice hash = hash_to_field(msg,2).
//   - signature, as element of E2(Fq2) 
// Assume signature is not point at infinity 
template CoreVerifyPubkeyG1(n, k){
``` 

If that is the case, for every message m, the  BLS verification of e(g1, signature) = e(pubkey, H(m)) is always true.

**Comment by jonathanpwang** [comment]
Hi, thanks for the comment! 

Currently our pubkey and signature are accepted as affine coordinates on the curve, (so in projective coordinates it is [x, y, 1]), so it is not possible for the inputs to be the point at infinity (which in projective coordinates is [0, 1, 0]). 

In the future we may add support for inputting pubkey and signature in the standard encoded hex format, in which case we will be sure to check for 0. 

Does this address the issue?
